### ISSUE TITLE
Open files with system's default music player

### ISSUE THREAD

**Issue by anotheredward** [96AA48/yplayer#6]
VLC doesn't support opus playback, so I tend to use mpv instead.
Would it make more sense to open the audio file with the system's default player instead of VLC?

**Comment by 96AA48** [comment]
I can add the option in the settings file if it helps. However, yplayer doesn't use VLC, it uses mplayer. :/

**Comment by anotheredward** [comment]
Ahk, Looks like my version of mplayer is one behind the latest, which now has opus support :).
Will have to go look at the brew recipe.
